dist: trusty
sudo: false
language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - libipc-run-perl
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- make
- make test
- make -C doc
- make install PREFIX=~/.local
- cd /
- u8strings /dev/null
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 u8strings | grep -A 10 -w U8STRINGS

# vim:ts=2 sts=2 sw=2 et
